starting_dist: 'uniform' #uniform or assist
num_tar: 5
threshold: 0.682
sim_types:
    param_tied_dir: True
    full_dir: True
graphs:
    theta_val: True
    gibbs_val: True
    sim_results_full: False
    sim_results_tied: True
    human_val: False
    convergence: False
